export const SET_TITLE = 'SET_TITLE'
export const ALERT = 'ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'
export const SET_REFERRER = 'SET_REFERRER'
export const CLEAR_REFERRER = 'CLEAR_REFERRER'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const RECEIVE_DISHES = 'RECEIVE_DISHES'

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const SUBMIT_COMMENT_SUCCESS = 'SUBMIT_COMMENT_SUCCESS'

export const UPDATE_USER = 'UPDATE_USER'

export const ADD_TO_CART = 'ADD_TO_CART'
export const DECR_CART_ITEM = 'DECR_CART_ITEM'
export const INCR_CART_ITEM = 'INCR_CART_ITEM'
export const CHECKOUT = 'CHECKOUT'
